apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logs-drilldown.fullname" . }}-grafana-provisioning
  labels:
    {{- include "logs-drilldown.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: gdev-testdata
        type: testdata
      - name: gdev-loki
        type: loki
        uid: gdev-loki
        isDefault: true
        access: proxy
        url: http://{{ include "logs-drilldown.fullname" . }}-loki:3100
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          derivedFields:
            - datasourceUid: gdev-tempo
              matcherRegex: traceID
              matcherType: label
              name: traceID-tempo
              url: "$${__value.raw}"
              urlDisplayLabel: tempo
        secureJsonData:
          httpHeaderValue1: {{ .Values.loki.tenantId | quote }}
      - name: gdev-tempo
        type: tempo
        uid: gdev-tempo
        access: proxy
        url: http://{{ include "logs-drilldown.fullname" . }}-tempo:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: gdev-loki
            spanStartTimeShift: -5m
            spanEndTimeShift: 5m
            customQuery: true
            query: '{service_name=~"tempo-ingester|tempo-distributor|pod-monitor-demo"} |="$${__span.traceId}"'
      - name: gdev-prometheus
        type: prometheus
        uid: gdev-prometheus
        access: proxy
        url: http://{{ include "logs-drilldown.fullname" . }}-prometheus:9090
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.55.1
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: gdev-tempo
          metricsToLogsV2:
            datasourceUid: gdev-loki
            customQuery: true
            query: '{service_name=~"tempo-ingester|tempo-distributor|pod-monitor-demo"}'
  apps.yaml: |
    apiVersion: 1
    apps:
      - type: grafana-lokiexplore-app
        org_id: 1
        org_name: Main Org.
        disabled: false
        jsonData:
          apiUrl: http://default-url.com
          isApiKeySet: true
        secureJsonData:
          apiKey: secret-key
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: logs-drilldown-local
        orgId: 1
        folder: Logs Drilldown local
        type: file
        disableDeletion: false
        updateIntervalSeconds: 5
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
